### ISSUE TITLE
Packagist shows dev branches

### ISSUE THREAD

**Issue by jrfnl** [TGMPA/TGM-Plugin-Activation#444]
Seems like a good idea to have packagist only show tagged releases if there is a config setting we can use for that.

https://packagist.org/packages/tgmpa/tgm-plugin-activation

![screenshot](http://snag.gy/vXH9H.jpg)

**Comment by GaryJones** [comment]
I don't think that's possible, and it's not necessarily a great idea anyway.

[Symfony framework](https://packagist.org/packages/symfony/framework-standard-edition) defaults to tagged release, but also shows the dev branches. This is the same behaviour as TGMPA on packagist. Some folks may want to try one of the dev or feature branches by pulling from composer instead of checking out from the repo, and that's up to them. Lower level theme and plugin developers are not going to be doing that, so that's fine.
