### ISSUE TITLE
Have more than 1 TGMPA backend notification

### ISSUE THREAD

**Issue by JakeHenshall** [TGMPA/TGM-Plugin-Activation#492]
Hi,

I'm wondering if there would be a way to include 2 separate notifications in the backend. 1 for the User and One For Developer as i'm creating a Theme Framework.

Thanks Jake.

**Comment by WebTechGlobal** [comment]
It possible. The approach used might depend on the notification but most of the time we use WordPress functions related to capabilities now rather than an admin OR user approach. Each role has different capabilities. So your admin can see a different notification from authors and authors see something different from subscribers. Keep in mind, technically authors or any other role, may still be users of a server and purchase goods etc.

Can you confirm, you do mean ALL notifications or is there a specific one? 

Also what difference do you want between those viewed by admin and other users?
