### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT

### ISSUE THREAD

**Issue by brankoconjic** [TGMPA/TGM-Plugin-Activation#529]
On some servers I'm getting this error:
<code>PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature</code>

It works if I upload the same .zip through Plugins > Add New.

Using WP 4.4.1 and TGMPA 2.5.2

Thanks!

**Comment by jrfnl** [comment]
Thanks for contacting us. Unfortunately there is not enough information for us to debug this.
Please read the guidelines for providing a [good bug report](https://github.com/TGMPA/TGM-Plugin-Activation/wiki/Guidelines-for-reporting-bugs) and add the relevant information.

**Comment by jrfnl** [comment]
@brankoconjic Is this still an issue ? If so, please provide us with more details. If not, let's close this issue.

**Comment by joje47** [comment]
Hi, since last update on this thread is not to old, I write here.

I experience the same issue, getting error: "PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature" when installing from Github. 
Installing from Wordpress using your plugin works flawlessly. When using my own zip-files to install in Wordpress it works perfectly, but when uploading the file to github, and then trying to install using TGMPA library I get above error. I tried uploading using git commandline, and uploading using web browser, same thing. 
If I download the archive from Github via right-click -> Save link as, and then install the plugin using wp upload from local computer, it works. So it does not seem to be a problem with the file on Github. It has to do with something else. I have plenty of space on my web server. I run WP 4.5.3 and when running this TGMPA library there are only original WP plugins there (Hello Dolly), and Akismet installed. No themes, except the ones shipped with WP. Fresh installation.  I do run WPMU, and installs this library as a plugin (ngo-install) as Network admin. Activating it, does not show anything in network admin mode, but when I go to blog id 1 (only blog present at install time) I see the notice. When clicking "Begin Installing plugins" I get the correct list. I mark everything (even tried one by one) and hit install. TGMPA installs everything from Wordpress, but gives above error on all GitHub stored plugins.
any idea how to mend this would be highly appreciated. My editition of the config file for TGMPA is to be found here: https://github.com/joje47/NGO-portal/blob/master/ngo-install/ngo-install.php

**Comment by jrfnl** [comment]
@joje47 The GitHub support is intended for plugins being developed and hosted on GH where the download would be the GH generated zip file for the repo and - last time I checked - works fine for that.

It was never intended for arbitrary zip files being uploaded to GH and yes, I wouldn't expect it to work for that.

**Comment by joje47** [comment]
These are plugins that installs normally using any other method, so I don't understand what you mean with artbitary zip files.. In what way are they more arbitrary then any other plugins? And in what way are they not developed and hosted on GH?
But I understand what you mean. Of course I could have a repo for every plugin, but I don't see the point, since the plugins are intended to be used together. That's why I wanted to make an installer. Will go looking for other options.
What bugs me is that there are  settings for installing "arbitrary external files" pointing to amazonaws in your example.php You are seriously saying that it can download from amazon, but not github? Whats the difference? 
Tried adding 'external_url' to plugin directory, but no luck. It has to point to a Github repository? (now "external_url" is  pointing to a folder within a github repos).

**Comment by jrfnl** [comment]
@joje47 I'm not saying it can't be done, I'm saying it's currently not supported. No need to get angry.

**Comment by joje47** [comment]
@jrfnl  Hi sorry. I'm not angry. I read your answer as a bit patronizing, that's why. Either way, it's a good snippet of code you have there, even if it doesn't support what I needed it to do. But now I know how to make it work, Thanks.

**Comment by jrfnl** [comment]
@joje47 Pull requests to improve TGMPA are always welcome ;-)
